name: Build, Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  lint:
    name: Lint code with ESLint
    runs-on: ubuntu-latest
    needs: test  # Solo se ejecuta si el job "test" tiene éxito

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . --ext .js

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: lint  # Solo se ejecuta si el job "lint" tiene éxito

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: joshuamsaechao/api-k8s-demo:latest,joshuamsaechao/api-k8s-demo:${{ github.sha }}

  deploy:
    name: Deploy to Minikube
    runs-on: self-hosted  # Runner autohospedado
    needs: build-and-push  # Solo se ejecuta si el job "build-and-push" tiene éxito

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/rbac.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Verify deployment
        run: |
          echo "Verifying pods in namespace demo-api..."
          kubectl get pods -n demo-api
